version: '3.8'

services:
  doc-parser-api:
    build: .
    container_name: doc-parser-fastapi
    ports:
      - "8080:8080"
    environment:
      - PYTHONPATH=/app
    volumes:
      # Mount source code for development (comment out for production)
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx reverse proxy (optional, for production)
  nginx:
    image: nginx:alpine
    container_name: doc-parser-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - doc-parser-api
    restart: unless-stopped
    profiles:
      - production

networks:
  default:
    name: doc-parser-network 